version: '3.8'

services:
  db:
    image: postgres:13
    container_name: mmd-db
    restart: always
    environment:
      POSTGRES_USER: mmduser
      POSTGRES_PASSWORD: mmdpass
      POSTGRES_DB: mmd_business
    ports:
      - "5432:5432"
    volumes:
      - mmd-business_pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mmd-business
    restart: always
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
      DATABASE_URL: postgresql://mmduser:mmdpass@mmd-db:5432/mmd_business
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    command: >
      sh -c "sleep 10 && flask run --host=0.0.0.0 --port=5000"

volumes:
  mmd-business_pgdata:

