services:
  db:
    image: postgres
    container_name: mmd-db
    environment:
      POSTGRES_USER: mmduser
      POSTGRES_PASSWORD: mmdpass
      POSTGRES_DB: mmd_business
    ports:
      - '5432:5432'
    networks:
      - mmd-network

  app:
    image: mmd-business
    container_name: mmd-business
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
    ports:
      - '5001:5000'
    networks:
      - mmd-network

networks:
  mmd-network:
    driver: bridge
